### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by alexey-sh** [webtorrent/webtorrent-cli#129]
Error: Command failed: /Applications/VLC.app/Contents/MacOS/VLC http://localhost:8000/0/d099d476ae8fac004804f76ae58ff81c56c152ee/%D0%90%D0%BB%D0%B0%D0%B4%D0%B4%D0%B8%D0%BD%20(2019)%20BDRip-AVC_ivanes.mkv --play-and-exit --quiet --video-on-top
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Applications/VLC.app/Contents/MacOS/VLC http://localhost:8000/0/d099d476ae8fac004804f76ae58ff81c56c152ee/%D0%90%D0%BB%D0%B0%D0%B4%D0%B4%D0%B8%D0%BD%20(2019)%20BDRip-AVC_ivanes.mkv --play-and-exit --quiet --video-on-top'

DEBUG INFO: webtorrent-cli 2.0.2, webtorrent 0.107.17, node v10.4.1, darwin x64, exit 1

**Comment by whtv** [comment]
This happens with mpv, too, if the filename contains any characters that are interpreted by the shell. It is fixed by adding double quotes around `${href}` in this line:
https://github.com/webtorrent/webtorrent-cli/blob/36a244877feb1be1244fd015876e92e02592b0a4/bin/cmd.js#L503
This should probably be done everywhere, that is `${href}` → `"${href}"`.

**Comment by ksnikiforov** [comment]
Have the same issue.

**Comment by rom1504** [comment]
Do you mean you have the same opportunity to do a pull request following
the above suggestion ? How lucky you are :)

**Comment by alxhotel** [comment]
Closed by #138
