### ISSUE TITLE
All files are being downloaded even after using --select index

### ISSUE THREAD

**Issue by souravndp** [webtorrent/webtorrent-cli#65]
Suppose a torrent has multiple files and I am trying to stream/download a particular file.

I used `webtorrent download 'magnet URI' -s 22 --mpv`

I expected that only relevant file (say 200 MB) will be downloaded. The selected video started streaming but in the background, the full torrent with all files (about 2.7 GB) was downloaded.

I have also tried downloading a single file without streaming and observed similar behaviour.

Webtorrent has `file.select()`, `file.deselect()` APIs. Still, why do all the files are being downloaded?

![capture](https://user-images.githubusercontent.com/652191/38053002-83dee14a-32f0-11e8-8445-61762658bab0.PNG)

**Comment by SilentBot1** [comment]
Hey @souravndp,

I just looked into this and this happens because files in the main WebTorrent library are all selected by default and with the current implementation in WebTorrent-cli, none of the files are deselected, leaving all selected by default even when specifying `-s` or `--select`.

I plan to have a PR for this issue done within the next few hours and to hopefully fix this issue.

**Comment by feross** [comment]
Fixed by https://github.com/webtorrent/webtorrent-cli/pull/74 and released to npm
