### ISSUE TITLE
option --out isn't consitent across subcommands

### ISSUE THREAD

**Issue by bricewge** [webtorrent/webtorrent-cli#79]
The help says `--out` is a path. However only the subcommand `download` expect the option's value to be a path, `create` and `info` assume it's a file.

It can cause some errors:
```
webtorrent-cli info sintel.torrent --out ./

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.11.1, webtorrent 0.99.4, node v6.14.3, linux x64, exit 1
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EISDIR: illegal operation on a directory, open '/home/bricewge/tmp'
    at Error (native)
```

**Comment by SilentBot1** [comment]
Hi @bricewge 

While I agree the parameters aren't consistent between the different sub-commands, this is by design as some commands require a directory path, such as downloading, and some require a file path, such as creating or downloading a torrent file.

If you would like to make it clearer for others in the future, the help page can be modified [here](https://github.com/webtorrent/webtorrent-cli/blob/master/bin/cmd.js#L265).

Kind regards
Brad
